version: "3.6"

services:
  node_js:
    image: "node_js:latest"
    command:
      - "-c"
      - "echo Container started\ntrap \"exit 0\" 15\n\nexec \"$$@\"\nwhile sleep 1 & wait $$!; do :; done"
      - "-"
    entrypoint:
      - "/bin/sh"
    volumes:
      - /dev/dri:/dev/dri
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - "DISPLAY=:0"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "SHELL=/bin/bash"
    ipc: "private"
    privileged: true
    hostname: node_js
    network_mode: "host"
    user: "andy"
    working_dir: "/home/andy"

